//
// Generated file, do not edit! Created by nedtool 4.6 from src/node/communication/routing/latorRouting/LatorRoutingDataPacket.msg.
//

#ifndef _LATORROUTINGDATAPACKET_M_H_
#define _LATORROUTINGDATAPACKET_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "PacketId_m.h"
// }}

/**
 * Class generated from <tt>src/node/communication/routing/latorRouting/LatorRoutingDataPacket.msg:25</tt> by nedtool.
 * <pre>
 * packet LatorDataPacket extends PacketId
 * {
 *     string destinationLator;
 * }
 * </pre>
 */
class LatorDataPacket : public ::PacketId
{
  protected:
    opp_string destinationLator_var;

  private:
    void copy(const LatorDataPacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const LatorDataPacket&);

  public:
    LatorDataPacket(const char *name=NULL, int kind=0);
    LatorDataPacket(const LatorDataPacket& other);
    virtual ~LatorDataPacket();
    LatorDataPacket& operator=(const LatorDataPacket& other);
    virtual LatorDataPacket *dup() const {return new LatorDataPacket(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual const char * getDestinationLator() const;
    virtual void setDestinationLator(const char * destinationLator);
};

inline void doPacking(cCommBuffer *b, LatorDataPacket& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, LatorDataPacket& obj) {obj.parsimUnpack(b);}


#endif // ifndef _LATORROUTINGDATAPACKET_M_H_

